apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cesi4-demo-java
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/AntoineCvlz/cesi-demo-boost-startup-java
    targetRevision: HEAD
    path: k8s/appli
  destination:
    server: https://kubernetes.default.svc
    namespace: cesi4
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
